build: 
	mkdir ../bin/Unitiger; cd ../bin/Unitiger; cmake ../../Unitiger; make; cp ../../Unitiger/src/Unitiger_wrapper.py Unitiger_wrapper.py

quick: 
	mkdir ../bin/Unitiger; cd ../bin/Unitiger; make; cp ../../Unitiger/src/Unitiger_wrapper.py Unitiger_wrapper.py	